## Colors configuration
[colors.primary]
background = "#1e2541"
foreground = "#eeffff"

[colors.normal]
black   = "#1e2541"
red     = "#f0719b"
green   = "#5af7b0"
yellow  = "#ffa56b"
blue    = "#57c7ff"
magenta = "#c792ea"
cyan    = "#89ddff"
white   = "#eeffff"

[colors.bright]
black   = "#354274"
red     = "#f02e6e"
green   = "#2ce592"
yellow  = "#ff8537"
blue    = "#1da0e2"
magenta = "#a742ea"
cyan    = "#47bae8"
white   = "#dee6e7"
